### ISSUE TITLE
Help command may result in an upload speed message

### ISSUE THREAD

**Issue by qexat** [Geoxor/Shaii#119]
Since help command returns a file, it somehow can send an upload speed message which is really annoying regarding command's purpose.

![image](https://user-images.githubusercontent.com/43090614/151321202-df1863fc-d2cd-487f-aebd-0401e0bde5e9.png)

**Comment by qexat** [comment]
Poor Niko :trollface:

**Comment by N1kO23** [comment]
Isn't this a feature of the bot when one has poor upload and the sending just fails?

**Comment by qexat** [comment]
> Isn't this a feature of the bot when one has poor upload and the sending just fails?

Yes, but it should not happen with a command like help

**Comment by N1kO23** [comment]
This happens because `help` command returns message object containing the file so it passes the if statement into the reply function.
```ts
// If the command returns void we just return
if (!result) return;
```
This function applies to all of the replies the bot does and the discord.js fails to send the reply. This can be due to poor upload or some other reasons, but nevertheless this error happens between discord and discord.js. Thus circulating around it isn't particularly simple.
```ts
// Send the result
message
  .reply(result)
  .catch(() => message.channel.send(result!))
  .catch((error) =>
    error.code === 500
      ? message.reply({
          embeds: [new Discord.MessageEmbed().setColor("#ffcc4d").setDescription("⚠️ when the upload speed")],
        })
      : message.reply(markdown(error))
  );
```
If one would want to prevent this on specific commands, the reply should happen inside the commands own function, which is probably not wanted inside this codebase (can't tell for sure as I am not particularly familiar with it or the guidelines of it)

Easiest workaround for now is to host the bot on a server that can handle uploading files that have the size of couple of kilobytes to prevent such occurence

**Comment by qexat** [comment]
I'm absolutely aware about the file upload stuff, the actual issue is that help command returns a file, while it should be an embed

**Comment by N1kO23** [comment]
That was not mentioned on the issue before now :trollface:

**Comment by qexat** [comment]
> That was not mentioned on the issue before now :trollface:

Yes, however I explicitely mentioned I knew what it was caused by

**Comment by N1kO23** [comment]
Help function now returns an embed instead of file, the embed can be for a specific category, for a specific function or just to list all functions. It can (and honestly should) be improved and stylished further.

Also for future issue reporting, please refer into https://tomasvotruba.com/blog/2019/07/08/7-tips-to-write-flawless-issue-report-on-github/ to be more clear to the maintainers with future issues

**Comment by qexat** [comment]
> Help function now returns an embed instead of file, the embed can be for a specific category, for a specific function or just to list all functions. It can (and honestly should) be improved and stylished further.
> 
> Also for future issue reporting, please refer into https://tomasvotruba.com/blog/2019/07/08/7-tips-to-write-flawless-issue-report-on-github/ to be more clear to the maintainers with future issues

Well, you should add an issue template to the repository then
