### ISSUE TITLE
!attack!attack!attack should also result to an attack

### ISSUE THREAD

**Issue by azur1s** [Geoxor/Shaii#56]
so we dont get fucked by discord with their asshat cooldown

**Comment by Geoxor** [comment]
we can simply check if the message includes "attack"

**Comment by azur1s** [comment]
litreally 2 minutes fix xd

**Comment by qexat** [comment]
!attack!attack!attack should also hit 3 times instead of only one

**Comment by Geoxor** [comment]
no because then people would spam !attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack!attack

**Comment by qexat** [comment]
should a limit then, to 5 for example

**Comment by Geoxor** [comment]
people would still spam it many times because its easier to hold CTRL + V

**Comment by Geoxor** [comment]
plus it kinda defeats the purpose of buying weapons and having skills

**Comment by qexat** [comment]
can't wait for weapons then :P
